Update search-post tool to function like Solr Post Tool (#14)
Resolves #13

diff --git a/src/main/resources/bin/search-post b/src/main/resources/bin/search-post
--- a/src/main/resources/bin/search-post
+++ b/src/main/resources/bin/search-post
@@ -1,98 +1,128 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+# Copyright 2019, California Institute of Technology ("Caltech").
+# U.S. Government sponsorship acknowledged.
 #
-# Copyright 2010-2014, by the California Institute of Technology.
-# ALL RIGHTS RESERVED. United States Government Sponsorship acknowledged.
-# Any commercial use must be negotiated with the Office of Technology Transfer
-# at the California Institute of Technology.
+# All rights reserved.
 #
-# This software is subject to U. S. export control laws and regulations
-# (22 C.F.R. 120-130 and 15 C.F.R. 730-774). To the extent that the software
-# is subject to U.S. export control laws and regulations, the recipient has
-# the responsibility to obtain export licenses or other export authority as
-# may be required before exporting such information to foreign countries or
-# providing access to foreign nationals.
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#
+# * Redistributions of source code must retain the above copyright notice,
+# this list of conditions and the following disclaimer.
+# * Redistributions must reproduce the above copyright notice, this list of
+# conditions and the following disclaimer in the documentation and/or other
+# materials provided with the distribution.
+# * Neither the name of Caltech nor its operating division, the Jet Propulsion
+# Laboratory, nor the names of its contributors may be used to endorse or
+# promote products derived from this software without specific prior written
+# permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
+# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+# POSSIBILITY OF SUCH DAMAGE.
 
-################################################################################
-# Set Environment Variables As Needed
-# REGISTRY_HOME=/path/to/registry
-# SOLR_HOME=/path/to/solr
-################################################################################
+COLLECTION="pds"
+PROPS=("-Dauto=yes")
+RECURSIVE=""
+FILES=()
 
-################################################################################
-# WARNING: Should not need to update below. Proceed with caution.
-################################################################################
+SCRIPT_DIR=$(cd "$( dirname $0 )" && pwd)
+PARENT_DIR=$(cd ${SCRIPT_DIR}/.. && pwd)
+LIB_DIR=${PARENT_DIR}/lib
+TOOL_JAR=(${LIB_DIR}/solr-core-*.jar)
 
-# Setup environment variables.
-SCRIPT_DIR=`cd "$( dirname $0 )" && pwd`
-PARENT_DIR=`cd ${SCRIPT_DIR}/.. && pwd`
-
-usage() {
-    echo
-    echo "$(basename $0) (docker or standalone) [optional:solr-docs-dir]" 1>&2
-    echo
-    exit 1
+function print_usage() {
+  echo ""
+  echo "Usage: $0 [OPTIONS] [SOLR-DOCS]"
+  echo ""
+  echo "Options:"
+  echo "  -h            Print Help"
+  echo "  -host <host>  Solr server host (default: localhost)"
+  echo "  -port <port>  Solr server port (default: 8983)"
+  echo ""
+  echo "Optional Parameters:"
+  echo "  SOLR-DOCS     solr-docs directory or an xml file"
+  echo ""
 }
 
-# Check arguments
-if [ $# -lt 1 ]; then
-    echo "ERROR: Missing argument." 1>&2
-    usage
-elif [ "$1" != "docker" ] && [ "$1" != "standalone" ]; then
-    echo "ERROR: Invalid argument." 1>&2
-    usage
-fi
+# Parse command line parameters
+while [ $# -gt 0 ]; do
+  if [[ -d "$1" ]]; then
+    # Directory
+    RECURSIVE=yes
+    FILES+=("$1")
+  elif [[ -f "$1" ]]; then
+    # File
+    FILES+=("$1")
+  else
+    if [[ "$1" == "-port" ]]; then
+      shift
+      PROPS+=("-Dport=$1")
+    elif [[ "$1" == "-host" ]]; then
+      shift
+      PROPS+=("-Dhost=$1")
+    elif [[ "$1" == "-h" ]]; then
+      print_usage
+      exit
+    else
+      echo -e "\nUnrecognized argument: $1\n"
+      exit 1
+    fi
+  fi
+  shift
+done
 
-install=$1
-registry_data=$2
+# No file / directory parameter
+if [[ "${#FILES[@]}" -eq 0 ]]; then
+  DEFAULT_DOCS_DIR=${HOME}/registry-data/solr-docs
+  echo "INFO:  No SOLR-DOCS parameter (Use -h flag for help)."
+  echo "INFO:  Looking for Solr documents in default location: ${DEFAULT_DOCS_DIR}"
 
-# Check Registry Data exists where expected
-if [ -z "${REGISTRY_HOME}" ]; then
-    REGISTRY_HOME=${PARENT_DIR}/../registry
-fi
-
-if [ -z "$registry_data" ]; then
-    registry_data=${REGISTRY_HOME}/../registry-data/solr-docs
-fi
-echo $registry_data
-
-# Check for Registry installation
-if [ ! -e "${REGISTRY_HOME}" ]; then
+  if [ ! -e "${DEFAULT_DOCS_DIR}" ]; then
     echo
-    echo "ERROR: Registry does not exist at ${REGISTRY_HOME}." 1>&2
-    echo "       Verify Registry has been installed and path is valid." 1>&2
-    echo "       If path to Registry differs, please update in this script." 1>&2
-    echo
-    exit 1
-fi
-
-if [ ! -e "${registry_data}" ]; then
-    echo
-    echo "ERROR: ${registry_data} does not exist as expected." 1>&2
+    echo "ERROR: ${DEFAULT_DOCS_DIR} does not exist." 1>&2
     echo "       Verify Registry installation completed successfully." 1>&2
     echo
     exit 1
+  fi
+
+  # Must be a directory
+  if [[ -d "${DEFAULT_DOCS_DIR}" ]]; then
+    RECURSIVE=yes
+    FILES+=("${DEFAULT_DOCS_DIR}")
+  else
+    echo "ERROR: ${DEFAULT_DOCS_DIR} must be a directory." 1>&2
+    exit 1
+  fi
+
+  echo "INFO:  Found Solr documents in ${REGISTRY_DATA}"
 fi
 
-# Execute Solr Post depending on installation method
-if [ "$install" == "standalone" ]; then
-    if [ -z "${SOLR_HOME}" ]; then
-	SOLR_HOME=${PARENT_DIR}/../solr-7.7.2
-    fi
-
-    if [ ! -d "${SOLR_HOME}" ]; then
-	echo
-	echo "ERROR: Solr does not exist at ${SOLR_HOME}." 1>&2
-	echo "       Verify Solr has been downloaded and unpackaged." 1>&2
-	echo "       If path to Solr Home differs, please add path to this script." 1>&2
-	echo
-	exit 1
-    fi
-
-    $SOLR_HOME/bin/post -c pds -params tr="add-hierarchy.xsl" $REGISTRY_DATA
-elif [ "$install" == "docker" ]; then
-    docker exec -it registry post -c pds -params "tr=add-hierarchy.xsl" /data/registry-data/solr-docs
+# Setup Java
+if [ -n "$JAVA_HOME" ]; then
+  JAVA="$JAVA_HOME/bin/java"
+else
+  JAVA=java
 fi
-    
 
-exit 0
+# Test that Java exists and is executable
+"$JAVA" -version >/dev/null 2>&1 || { echo >&2 "Java is required to run this tool! Please install Java 8 or greater before running this script."; exit 1; }
 
+# Parameters for Solr post tool
+PROPS+=("-Dc=$COLLECTION" "-Ddata=files")
+if [[ -n "$RECURSIVE" ]]; then
+  PROPS+=("-Drecursive=yes")
+fi
+
+# Call Solr post tool
+echo "$JAVA" -classpath "${TOOL_JAR[0]}" "${PROPS[@]}" org.apache.solr.util.SimplePostTool "${FILES[@]}"
+"$JAVA" -classpath "${TOOL_JAR[0]}" "${PROPS[@]}" org.apache.solr.util.SimplePostTool "${FILES[@]}"
